wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1674372402.959994
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.16
      5: 0.13.9
      8:
      - 5
dim:
  desc: null
  value: 2
epochs:
  desc: null
  value: 1000
kernel:
  desc: null
  value: rbf
lr:
  desc: null
  value: 0.001
lscale_1:
  desc: null
  value: 1.0
lscale_2:
  desc: null
  value: 1.0
lscale_3:
  desc: null
  value: null
lscale_4:
  desc: null
  value: null
noise:
  desc: null
  value: 0.11
